import sys
import re
import os

def parse_cpp_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Remove single-line and multi-line comments to simplify parsing
    content = re.sub(r'//.*', '', content)
    content = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL)
    
    classes = []
    
    # Regex to find: class or struct
    # followed by optional other attributes or whitespace
    # followed by [[jnl::SOMETHING]] (with optional {})
    # followed by optional other attributes or whitespace
    # followed by ClassName
    
    # Alternatively, the attribute can be BEFORE the class/struct keyword.
    # Let's just find [[jnl::...]] and then look for the class/struct keyword and identifier.
    # Actually, a unified approach:
    # Look for [[jnl::...]] attribute.
    # Then it could be followed by `class` or `struct` (if it was placed before the class)
    # OR it could be preceded by `class` or `struct` (if placed after).
    # Since we removed comments, we can just look for the `class` or `struct` keyword,
    # then any mix of attributes `[[...]]` or `__attribute__(...)` or `alignas(...)`,
    # then the identifier.
    
    # Let's match `class` or `struct`, then any whitespace/attributes, then the identifier.
    # We will capture the stuff between the keyword and identifier to check if it has jnl::
    # Or if jnl:: is BEFORE the class keyword, we should catch that too.
    
    # Regex: 
    # (?:\[\[\s*jnl::[a-zA-Z0-9_{}]+\s*\]\]\s*(?:\[\[.*?\]\]\s*)*)?   # optional pre-attributes
    # (class|struct)\s+                                              # keyword
    # ((?:\[\[.*?\]\]\s*)*)                                          # post-attributes
    # ([a-zA-Z_][a-zA-Z0-9_]*)                                       # identifier
    
    # Let's use a simpler regex that matches both:
    pattern = re.compile(
        r'(?:\[\[\s*=jnl::[a-zA-Z0-9_{}()]*\s*\]\]\s*(?:\[\[.*?\]\]\s*)*)?' # Pre-attributes
        r'\b(class|struct)\b\s+'                                          # class or struct
        r'((?:\[\[.*?\]\]\s*)*)?'                                         # Post-attributes
        r'([a-zA-Z_][a-zA-Z0-9_]*)',                                      # Class name
        re.DOTALL
    )
    
    for match in pattern.finditer(content):
        full_match = match.group(0)
        class_name = match.group(3)
        if '=jnl::' in full_match:
            classes.append(class_name)
            
    return classes

def main():
    if len(sys.argv) < 3:
        print("Usage: python jnl_parser.py <output_cpp> <input_headers...>")
        sys.exit(1)
        
    output_cpp = sys.argv[1]
    input_files = sys.argv[2:]
    
    exported_classes = []
    headers_with_exports = []
    
    for f in input_files:
        classes = parse_cpp_file(f)
        if classes:
            exported_classes.extend(classes)
            headers_with_exports.append(f)
            
    # Generate the C++ file
    with open(output_cpp, 'w', encoding='utf-8') as out:
        out.write("// Auto-generated by JavaNativeLink parser\n")
        out.write("#include <fstream>\n")
        out.write("#include <iostream>\n")
        out.write("#include \"JavaNativeLink/JavaGenerator.h\"\n\n")
        
        for h in headers_with_exports:
            # We include the absolute or relative path, or just assume the compiler knows the include path.
            # Usually, CMake passes absolute paths to this script.
            out.write(f'#include "{os.path.abspath(h)}"\n')
            
        out.write("\nint main(int argc, char** argv) {\n")
        if not exported_classes:
            out.write("    std::cout << \"No JNL exported classes found.\\n\";\n")
            out.write("    return 0;\n")
            out.write("}\n")
            return

        out.write("    if (argc < 2) {\n")
        out.write("        std::cerr << \"Usage: \" << argv[0] << \" <output_dir>\\n\";\n")
        out.write("        return 1;\n")
        out.write("    }\n")
        out.write("    std::string out_dir = argv[1];\n\n")
        
        for c in exported_classes:
            out.write(f'    {{\n')
            out.write(f'        std::string out_file = out_dir + "/{c}.java";\n')
            out.write(f'        std::ofstream out(out_file);\n')
            out.write(f'        JNL::generate_java<{c}>(out, "", "{c}");\n')
            out.write(f'        std::cout << "Generated " << out_file << "\\n";\n')
            out.write(f'    }}\n')
            
        out.write("    return 0;\n")
        out.write("}\n")

if __name__ == "__main__":
    main()
